### ISSUE TITLE
Move tests to a separate repository

### ISSUE THREAD

**Issue by hoshsadiq** [TYVRNET/SRL#27]
It makes it easier and better to write tests among the different languages and ensures consistency. We could use a simple syntax similar to [SimpleTest](http://simpletest.org/). This allows the language to separately interpret the test files, use the language's code to run the test and ensure the correct stuff is matched (and correct regex is generated). The current `.rule` syntax may be good enough for this.

**Comment by KarimGeiger** [comment]
Moving tests to a separate repository is a good idea. I'll do that tomorrow. For the test syntax: It should definitely be something easy to parse no matter what language you're using, since they should be universal for all implementations. I was thinking about using [YAML](https://en.wikipedia.org/wiki/YAML) instead of the current selfmade syntax in the `.rule` files.
